/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BloodType = IDL.Variant({
  'AB_Neg' : IDL.Null,
  'AB_Pos' : IDL.Null,
  'B_Neg' : IDL.Null,
  'B_Pos' : IDL.Null,
  'A_Neg' : IDL.Null,
  'A_Pos' : IDL.Null,
  'O_Neg' : IDL.Null,
  'O_Pos' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Donor = IDL.Record({
  'id' : IDL.Nat,
  'bloodType' : BloodType,
  'name' : IDL.Text,
  'lastDonationDate' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'totalDonations' : IDL.Nat,
  'contactPhone' : IDL.Text,
});
export const BloodRequest = IDL.Record({
  'id' : IDL.Nat,
  'hospital' : IDL.Text,
  'status' : IDL.Text,
  'bloodType' : BloodType,
  'urgency' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'units' : IDL.Nat,
  'patientName' : IDL.Text,
  'requestedBy' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'urgentRequests' : IDL.Nat,
  'pendingRequests' : IDL.Nat,
  'activeDonors' : IDL.Nat,
  'totalInventoryUnits' : IDL.Nat,
  'unitsCollectedToday' : IDL.Nat,
  'totalDonors' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BloodType],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBloodRequest' : IDL.Func(
      [IDL.Text, BloodType, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deactivateDonor' : IDL.Func([IDL.Nat], [], []),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDonor' : IDL.Func([IDL.Nat], [IDL.Opt(Donor)], ['query']),
  'getInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(BloodType, IDL.Nat))],
      ['query'],
    ),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
  'getRequest' : IDL.Func([IDL.Nat], [IDL.Opt(BloodRequest)], ['query']),
  'getUrgentRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDonors' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
  'updateDonor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, BloodType],
      [],
      [],
    ),
  'updateInventory' : IDL.Func([BloodType, IDL.Nat], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BloodType = IDL.Variant({
    'AB_Neg' : IDL.Null,
    'AB_Pos' : IDL.Null,
    'B_Neg' : IDL.Null,
    'B_Pos' : IDL.Null,
    'A_Neg' : IDL.Null,
    'A_Pos' : IDL.Null,
    'O_Neg' : IDL.Null,
    'O_Pos' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Donor = IDL.Record({
    'id' : IDL.Nat,
    'bloodType' : BloodType,
    'name' : IDL.Text,
    'lastDonationDate' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'totalDonations' : IDL.Nat,
    'contactPhone' : IDL.Text,
  });
  const BloodRequest = IDL.Record({
    'id' : IDL.Nat,
    'hospital' : IDL.Text,
    'status' : IDL.Text,
    'bloodType' : BloodType,
    'urgency' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'units' : IDL.Nat,
    'patientName' : IDL.Text,
    'requestedBy' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'urgentRequests' : IDL.Nat,
    'pendingRequests' : IDL.Nat,
    'activeDonors' : IDL.Nat,
    'totalInventoryUnits' : IDL.Nat,
    'unitsCollectedToday' : IDL.Nat,
    'totalDonors' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BloodType],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBloodRequest' : IDL.Func(
        [IDL.Text, BloodType, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deactivateDonor' : IDL.Func([IDL.Nat], [], []),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDonor' : IDL.Func([IDL.Nat], [IDL.Opt(Donor)], ['query']),
    'getInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(BloodType, IDL.Nat))],
        ['query'],
      ),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
    'getRequest' : IDL.Func([IDL.Nat], [IDL.Opt(BloodRequest)], ['query']),
    'getUrgentRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDonors' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
    'updateDonor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, BloodType],
        [],
        [],
      ),
    'updateInventory' : IDL.Func([BloodType, IDL.Nat], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };