/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BloodRequest {
  'id' : bigint,
  'hospital' : string,
  'status' : string,
  'bloodType' : BloodType,
  'urgency' : string,
  'createdAt' : bigint,
  'notes' : string,
  'units' : bigint,
  'patientName' : string,
  'requestedBy' : string,
}
export type BloodType = { 'AB_Neg' : null } |
  { 'AB_Pos' : null } |
  { 'B_Neg' : null } |
  { 'B_Pos' : null } |
  { 'A_Neg' : null } |
  { 'A_Pos' : null } |
  { 'O_Neg' : null } |
  { 'O_Pos' : null };
export interface DashboardStats {
  'urgentRequests' : bigint,
  'pendingRequests' : bigint,
  'activeDonors' : bigint,
  'totalInventoryUnits' : bigint,
  'unitsCollectedToday' : bigint,
  'totalDonors' : bigint,
}
export interface Donor {
  'id' : bigint,
  'bloodType' : BloodType,
  'name' : string,
  'lastDonationDate' : string,
  'isActive' : boolean,
  'email' : string,
  'totalDonations' : bigint,
  'contactPhone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonor' : ActorMethod<[string, string, string, BloodType], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBloodRequest' : ActorMethod<
    [string, BloodType, bigint, string, string, string, string],
    bigint
  >,
  'deactivateDonor' : ActorMethod<[bigint], undefined>,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getAllRequests' : ActorMethod<[], Array<BloodRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDonor' : ActorMethod<[bigint], [] | [Donor]>,
  'getInventory' : ActorMethod<[], Array<[BloodType, bigint]>>,
  'getPendingRequests' : ActorMethod<[], Array<BloodRequest>>,
  'getRequest' : ActorMethod<[bigint], [] | [BloodRequest]>,
  'getUrgentRequests' : ActorMethod<[], Array<BloodRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDonors' : ActorMethod<[string], Array<Donor>>,
  'updateDonor' : ActorMethod<
    [bigint, string, string, string, BloodType],
    undefined
  >,
  'updateInventory' : ActorMethod<[BloodType, bigint], undefined>,
  'updateRequestStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];