/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donor {
    id: bigint;
    bloodType: BloodType;
    name: string;
    lastDonationDate: string;
    isActive: boolean;
    email: string;
    totalDonations: bigint;
    contactPhone: string;
}
export interface DashboardStats {
    urgentRequests: bigint;
    pendingRequests: bigint;
    activeDonors: bigint;
    totalInventoryUnits: bigint;
    unitsCollectedToday: bigint;
    totalDonors: bigint;
}
export interface UserProfile {
    name: string;
}
export interface BloodRequest {
    id: bigint;
    hospital: string;
    status: string;
    bloodType: BloodType;
    urgency: string;
    createdAt: bigint;
    notes: string;
    units: bigint;
    patientName: string;
    requestedBy: string;
}
export enum BloodType {
    AB_Neg = "AB_Neg",
    AB_Pos = "AB_Pos",
    B_Neg = "B_Neg",
    B_Pos = "B_Pos",
    A_Neg = "A_Neg",
    A_Pos = "A_Pos",
    O_Neg = "O_Neg",
    O_Pos = "O_Pos"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonor(name: string, contactPhone: string, email: string, bloodType: BloodType): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBloodRequest(patientName: string, bloodType: BloodType, units: bigint, hospital: string, urgency: string, requestedBy: string, notes: string): Promise<bigint>;
    deactivateDonor(id: bigint): Promise<void>;
    getAllDonors(): Promise<Array<Donor>>;
    getAllRequests(): Promise<Array<BloodRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDonor(id: bigint): Promise<Donor | null>;
    getInventory(): Promise<Array<[BloodType, bigint]>>;
    getPendingRequests(): Promise<Array<BloodRequest>>;
    getRequest(id: bigint): Promise<BloodRequest | null>;
    getUrgentRequests(): Promise<Array<BloodRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDonors(searchText: string): Promise<Array<Donor>>;
    updateDonor(id: bigint, name: string, contactPhone: string, email: string, bloodType: BloodType): Promise<void>;
    updateInventory(bloodType: BloodType, units: bigint): Promise<void>;
    updateRequestStatus(id: bigint, status: string): Promise<void>;
}
import type { BloodRequest as _BloodRequest, BloodType as _BloodType, Donor as _Donor, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonor(arg0: string, arg1: string, arg2: string, arg3: BloodType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonor(arg0, arg1, arg2, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonor(arg0, arg1, arg2, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBloodRequest(arg0: string, arg1: BloodType, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBloodRequest(arg0, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBloodRequest(arg0, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deactivateDonor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateDonor(arg0);
            return result;
        }
    }
    async getAllDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonors();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonors();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<BloodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDonor(arg0: bigint): Promise<Donor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonor(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonor(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(): Promise<Array<[BloodType, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRequests(): Promise<Array<BloodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRequests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRequests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequest(arg0: bigint): Promise<BloodRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequest(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequest(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUrgentRequests(): Promise<Array<BloodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUrgentRequests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUrgentRequests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchDonors(arg0: string): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonors(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonors(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonor(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: BloodType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonor(arg0, arg1, arg2, arg3, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonor(arg0, arg1, arg2, arg3, to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateInventory(arg0: BloodType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(to_candid_BloodType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateRequestStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BloodRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequest): BloodRequest {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BloodType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodType): BloodType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donor]): Donor | null {
    return value.length === 0 ? null : from_candid_Donor_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BloodRequest]): BloodRequest | null {
    return value.length === 0 ? null : from_candid_BloodRequest_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hospital: string;
    status: string;
    bloodType: _BloodType;
    urgency: string;
    createdAt: bigint;
    notes: string;
    units: bigint;
    patientName: string;
    requestedBy: string;
}): {
    id: bigint;
    hospital: string;
    status: string;
    bloodType: BloodType;
    urgency: string;
    createdAt: bigint;
    notes: string;
    units: bigint;
    patientName: string;
    requestedBy: string;
} {
    return {
        id: value.id,
        hospital: value.hospital,
        status: value.status,
        bloodType: from_candid_BloodType_n8(_uploadFile, _downloadFile, value.bloodType),
        urgency: value.urgency,
        createdAt: value.createdAt,
        notes: value.notes,
        units: value.units,
        patientName: value.patientName,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bloodType: _BloodType;
    name: string;
    lastDonationDate: string;
    isActive: boolean;
    email: string;
    totalDonations: bigint;
    contactPhone: string;
}): {
    id: bigint;
    bloodType: BloodType;
    name: string;
    lastDonationDate: string;
    isActive: boolean;
    email: string;
    totalDonations: bigint;
    contactPhone: string;
} {
    return {
        id: value.id,
        bloodType: from_candid_BloodType_n8(_uploadFile, _downloadFile, value.bloodType),
        name: value.name,
        lastDonationDate: value.lastDonationDate,
        isActive: value.isActive,
        email: value.email,
        totalDonations: value.totalDonations,
        contactPhone: value.contactPhone
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BloodType, bigint]): [BloodType, bigint] {
    return [
        from_candid_BloodType_n8(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AB_Neg: null;
} | {
    AB_Pos: null;
} | {
    B_Neg: null;
} | {
    B_Pos: null;
} | {
    A_Neg: null;
} | {
    A_Pos: null;
} | {
    O_Neg: null;
} | {
    O_Pos: null;
}): BloodType {
    return "AB_Neg" in value ? BloodType.AB_Neg : "AB_Pos" in value ? BloodType.AB_Pos : "B_Neg" in value ? BloodType.B_Neg : "B_Pos" in value ? BloodType.B_Pos : "A_Neg" in value ? BloodType.A_Neg : "A_Pos" in value ? BloodType.A_Pos : "O_Neg" in value ? BloodType.O_Neg : "O_Pos" in value ? BloodType.O_Pos : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodRequest>): Array<BloodRequest> {
    return value.map((x)=>from_candid_BloodRequest_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BloodType, bigint]>): Array<[BloodType, bigint]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BloodType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): _BloodType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): {
    AB_Neg: null;
} | {
    AB_Pos: null;
} | {
    B_Neg: null;
} | {
    B_Pos: null;
} | {
    A_Neg: null;
} | {
    A_Pos: null;
} | {
    O_Neg: null;
} | {
    O_Pos: null;
} {
    return value == BloodType.AB_Neg ? {
        AB_Neg: null
    } : value == BloodType.AB_Pos ? {
        AB_Pos: null
    } : value == BloodType.B_Neg ? {
        B_Neg: null
    } : value == BloodType.B_Pos ? {
        B_Pos: null
    } : value == BloodType.A_Neg ? {
        A_Neg: null
    } : value == BloodType.A_Pos ? {
        A_Pos: null
    } : value == BloodType.O_Neg ? {
        O_Neg: null
    } : value == BloodType.O_Pos ? {
        O_Pos: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
